apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-bfhc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0058-tenant/tkrw-pr712-0075-0058-app/devfile-sample-bfhc@sha256:a81ff668dfa1a31e206a11d29c1785c333f63300648f348eec7f99b9c940b9e9
        name: my-nodejs
        resources: {}
status: {}
